import { useNavigate as tsNavigate, useLocation as tsLocation, useParams as tsParams, useRouter, Link as TSLink, Navigate as TSNavigate, Outlet as TSOutlet } from "@tanstack/react-router";
import { useMemo, useCallback, forwardRef, type ComponentProps, type ReactNode } from "react";
function parseTo(to: string) { const [beforeHash, hash] = (to ?? "").split("#"); const [pathname, search] = beforeHash.split("?"); return { pathname: pathname || ".", search: search ? Object.fromEntries(new URLSearchParams(search)) : undefined, hash: hash || undefined }; }
type NavigateOptions = { replace?: boolean; state?: unknown }; type NavigateFn = { (to: string | number, options?: NavigateOptions): void; (delta: number): void };
export function useNavigate(): NavigateFn { const nav = tsNavigate(); const router = useRouter(); return useCallback((to: string | number, options?: NavigateOptions) => { if (typeof to === "number") return router.history.go(to); const p = parseTo(to); nav({ to: p.pathname, search: p.search as never, hash: p.hash, state: options?.state as never, replace: options?.replace }); }, [nav, router]) as NavigateFn; }
export function useLocation() { const loc = tsLocation(); return useMemo(() => ({ pathname: loc.pathname, search: loc.searchStr ? `?${loc.searchStr}` : "", hash: loc.hash ?? "", state: loc.state ?? null, key: loc.pathname + (loc.searchStr ?? "") }), [loc]); }
export function useParams<T extends Record<string, string | undefined> = Record<string, string | undefined>>(): T { return tsParams({ strict: false } as never) as T; }
export function useSearchParams(): [URLSearchParams, (init: URLSearchParams | Record<string, string> | ((prev: URLSearchParams) => URLSearchParams), opts?: { replace?: boolean }) => void] { const loc = tsLocation(); const nav = tsNavigate(); const router = useRouter(); const params = useMemo(() => new URLSearchParams(loc.searchStr ?? ""), [loc.searchStr]); const set = useCallback((init: URLSearchParams | Record<string,string> | ((prev:URLSearchParams)=>URLSearchParams), opts?:{replace?:boolean}) => { const live = router.state.location; const current = new URLSearchParams(live.searchStr ?? ""); const next = typeof init === "function" ? init(current) : init instanceof URLSearchParams ? init : new URLSearchParams(init); nav({ to: live.pathname, search: Object.fromEntries(next) as never, replace: opts?.replace }); }, [nav, router]); return [params, set]; }
type LinkProps = Omit<ComponentProps<typeof TSLink>, "to"> & { to: string; replace?: boolean; state?: unknown; children?: ReactNode };
export const Link = forwardRef<HTMLAnchorElement, LinkProps>(function Link({ to, replace, state, children, ...rest }, ref) { const p = parseTo(to); const props = rest as Record<string, unknown>; return <TSLink ref={ref as never} to={p.pathname as never} search={p.search as never} hash={p.hash} replace={replace} state={state as never} {...props}>{children}</TSLink>; });
export function Navigate({ to, replace, state }: { to:string; replace?:boolean; state?:unknown }) { const p = parseTo(to); return <TSNavigate to={p.pathname as never} search={p.search as never} hash={p.hash} state={state as never} replace={replace}/>; }
export const Outlet = TSOutlet;
export const NavLink = Link;