import {
  BarChart3,
  Zap,
  Shield,
  ClipboardList,
  ShoppingBag,
  Gavel,
  Camera,
  Heart,
  Printer,
  UserCheck,
  Timer,
  FileText,
} from "lucide-react";
import salesHero from "@/assets/sales-hero.jpg";
import salesCheckin from "@/assets/sales-checkin.jpg";
import salesScoring from "@/assets/sales-scoring.jpg";
import demoWebsite from "@/assets/demo-website-builder.jpg";
import demoRegistration from "@/assets/demo-registration.jpg";
import demoPairings from "@/assets/demo-pairings.jpg";
import demoBudget from "@/assets/demo-budget.jpg";
import demoMessaging from "@/assets/demo-messaging.jpg";
import demoSponsors from "@/assets/demo-sponsors.jpg";

export const slides = [
  {
    id: "title",
    type: "title" as const,
    heading: "TeeVents",
    subheading: "The All-In-One Golf Tournament Management Platform",
    tagline: "Plan. Promote. Play. — Everything your tournament needs in one place.",
    bgImage: salesHero,
  },
  {
    id: "problem",
    type: "bullets" as const,
    heading: "The Problem",
    icon: BarChart3,
    color: "hsl(var(--destructive))",
    bullets: [
      "Managing golf tournaments involves dozens of disconnected tools",
      "Spreadsheets for players, email for communications, separate payment processors",
      "No single platform built specifically for golf tournament organizers",
      "Hours wasted on manual coordination instead of building your event",
    ],
  },
  {
    id: "solution",
    type: "bullets" as const,
    heading: "The Solution: TeeVents",
    icon: Zap,
    color: "hsl(var(--primary))",
    bullets: [
      "Purpose-built platform for golf tournament management",
      "From website creation to live scoring — everything in one dashboard",
      "Start free, scale as you grow with tiered pricing",
      "Organizers collect payments directly with Stripe Connect",
    ],
  },
  {
    id: "website",
    type: "feature" as const,
    heading: "Tournament Website Builder",
    description: "Create a beautiful, branded tournament website in minutes. Choose from 3 professional templates, customize colors and content, publish with one click, and connect your own custom domain for a fully branded experience.",
    image: demoWebsite,
    highlights: ["3 Pro Templates", "Custom Domain Support", "One-Click Publish", "Mobile Responsive"],
  },
  {
    id: "registration",
    type: "feature" as const,
    heading: "Online Registration & Payments",
    description: "Accept player registrations and payments online with Stripe Connect. Customize your form with add-on items (mulligans, dinner tickets), custom fields, and tournament promo codes. Automated confirmations and real-time payment tracking.",
    image: demoRegistration,
    highlights: ["Registration Add-Ons", "Custom Fields & Promo Codes", "Stripe Payments", "Auto Confirmations"],
  },
  {
    id: "pairings",
    type: "feature" as const,
    heading: "Player Pairings & Groups",
    description: "Drag-and-drop player assignments into groups. Auto-assign players, create foursomes, and manage the entire roster with CSV import/export.",
    image: demoPairings,
    highlights: ["Drag & Drop", "Auto-Assign", "CSV Import/Export", "Group Management"],
  },
  {
    id: "scoring",
    type: "feature" as const,
    heading: "Live Scoring & Leaderboard",
    description: "Players scan a QR code printed on their scorecard to instantly access their group's scoring page — no manual login needed. They enter scores hole by hole on any device. Supports 8 formats including Scramble, Best Ball, Stableford, Alternate Shot, and Shamble. Leaderboard updates in real-time with sponsor rotations.",
    image: salesScoring,
    highlights: ["QR Code Auto-Login", "8 Scoring Formats", "Real-Time Leaderboard", "Sponsor Rotations"],
  },
  {
    id: "printable-scorecard",
    type: "feature" as const,
    heading: "Print-Ready Scorecards with QR Codes",
    description: "Every scorecard comes with an embedded QR code that players scan to instantly log in to live scoring. No usernames, no passwords—just scan, play, and score in real-time. Choose from 6 customizable scorecard layouts and print directly from the platform.",
    image: salesCheckin,
    highlights: ["Embedded QR Codes", "Instant Player Login", "6 Layout Options", "Print-Ready PDF", "Custom Branding"],
  },
  {
    id: "checkin",
    type: "feature" as const,
    heading: "QR Code Check-In",
    description: "Print QR codes for every player. Staff scan at check-in using any device with our dedicated Scan Station page. Real-time check-in counter with manual search fallback.",
    image: salesCheckin,
    highlights: ["QR Code Generation", "Dedicated Scan Station", "Real-Time Counter", "Manual Search"],
  },
  {
    id: "sponsors",
    type: "feature" as const,
    heading: "Sponsor Management",
    description: "Track sponsors by tier (Title, Gold, Silver, Bronze), manage payments, display logos on your tournament website, and generate sponsor reports.",
    image: demoSponsors,
    highlights: ["Tiered Sponsorships", "Payment Tracking", "Website Display", "Logo Management"],
  },
  {
    id: "budget",
    type: "feature" as const,
    heading: "Budget Tracking",
    description: "Track every dollar — income and expenses — with categorized budget items. See paid vs. unpaid status at a glance and keep your financials organized.",
    image: demoBudget,
    highlights: ["Income & Expenses", "Categories", "Paid/Unpaid Status", "Real-Time Totals"],
  },
  {
    id: "messaging",
    type: "feature" as const,
    heading: "Email & SMS Messaging",
    description: "Send targeted communications to your entire player roster. Schedule messages in advance, track delivery, and keep everyone informed with email and SMS.",
    image: demoMessaging,
    highlights: ["Email Blasts", "SMS Texting", "Scheduled Sends", "Delivery Tracking"],
  },
  {
    id: "advanced",
    type: "iconGrid" as const,
    heading: "Advanced Features",
    icon: Zap,
    description: "Unlock powerful tools to elevate your tournament experience and maximize fundraising.",
    gridItems: [
      { icon: ShoppingBag, label: "Merchandise Store" },
      { icon: Gavel, label: "Auction & Raffle" },
      { icon: Camera, label: "Photo Gallery" },
      { icon: Heart, label: "Donation Page" },
      { icon: Printer, label: "6 Printable Types" },
      { icon: UserCheck, label: "Volunteer Coordination" },
      { icon: Timer, label: "Countdown Styles" },
      { icon: FileText, label: "Surveys & Feedback" },
      { icon: ClipboardList, label: "Planning Guide" },
    ],
  },
  {
    id: "planning",
    type: "bullets" as const,
    heading: "Built-In Planning & Printables",
    icon: ClipboardList,
    color: "hsl(var(--primary))",
    bullets: [
      "30-item planning checklist auto-generated for every tournament",
      "6 printable types: scorecards, cart signs, name badges, sponsor signs, alpha list & hole assignments",
      "Registration add-ons (mulligans, dinner tickets) and tournament promo codes",
      "Custom registration fields — collect exactly the data you need",
      "4 countdown timer styles and hole-by-hole par customization",
    ],
  },
  {
    id: "pricing",
    type: "pricing" as const,
    heading: "Simple, Transparent Pricing",
    plans: [
      { name: "Base", price: "Free", fee: "Stripe fees only", highlights: ["1 tournament", "Registration with add-ons & promo codes", "Website (1 template)", "Leaderboard (Stroke Play & Best Ball)", "QR check-in & planning guide"] },
      { name: "Starter", price: "$499", fee: "Stripe fees only", popular: true, highlights: ["All 6 templates + custom colors", "All 8 scoring formats", "Sponsors, budget & donations", "6 printable types, SMS & countdown styles"] },
      { name: "Pro", price: "$999", fee: "Stripe fees only", highlights: ["Merch store & auctions", "Surveys & volunteers", "Custom print fonts & layouts", "Priority support"] },
      { name: "Enterprise", price: "Custom", fee: "Stripe fees only", highlights: ["Unlimited tournaments", "Unlimited SMS", "White-label branding", "API access"] },
    ],
  },
  {
    id: "security",
    type: "bullets" as const,
    heading: "Enterprise-Grade Infrastructure",
    icon: Shield,
    color: "hsl(var(--primary))",
    bullets: [
      "Stripe Connect for secure, PCI-compliant payment processing",
      "Row-Level Security on all database tables",
      "Organizers manage their own Stripe accounts — full control",
      "Cloud-native architecture that scales with your event",
    ],
  },
  {
    id: "cta",
    type: "cta" as const,
    heading: "Ready to Elevate Your Tournament?",
    subheading: "Join organizers who save 20+ hours per event with TeeVents.",
    cta: "Get Started Free",
    url: "/get-started",
    bgImage: salesHero,
  },
];
