import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { redeemTeamLoginCode } from "@/lib/teamLogin.functions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Loader2, KeyRound, Mail } from "lucide-react";

export default function TeamLogin() {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [code, setCode] = useState("");
  const [emailLoading, setEmailLoading] = useState(false);
  const [codeLoading, setCodeLoading] = useState(false);

  const submitEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim() || !password) {
      toast.error("Enter your email and password");
      return;
    }
    setEmailLoading(true);
    const { error } = await supabase.auth.signInWithPassword({
      email: email.trim().toLowerCase(),
      password,
    });
    setEmailLoading(false);
    if (error) {
      toast.error(error.message || "Could not sign you in");
      return;
    }
    navigate("/dashboard");
  };

  const submitCode = async (e: React.FormEvent) => {
    e.preventDefault();
    const clean = code.trim().toUpperCase();
    if (clean.length !== 6) {
      toast.error("Enter your 6-character login code");
      return;
    }
    setCodeLoading(true);
    try {
      const result = await redeemTeamLoginCode({ data: { code: clean } });
      const { error } = await supabase.auth.verifyOtp({
        token_hash: result.token_hash,
        type: "magiclink",
      });
      if (error) throw new Error(error.message);
      toast.success(`Signed in as ${result.email}`);
      navigate("/dashboard");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Login failed");
    } finally {
      setCodeLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-background">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="mx-auto mb-3 h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
            <KeyRound className="h-6 w-6 text-primary" />
          </div>
          <CardTitle>Team Member Login</CardTitle>
          <p className="text-sm text-muted-foreground">
            Sign in with your email and password, or use the login code your organizer gave you.
          </p>
        </CardHeader>
        <CardContent className="space-y-5">
          {/* Login code */}
          <div className="rounded-md border p-4 space-y-3">
            <p className="text-sm font-semibold flex items-center gap-2">
              <KeyRound className="h-4 w-4" /> Use Login Code
            </p>
            <form onSubmit={submitCode} className="space-y-3">
              <Input
                autoFocus
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))}
                placeholder="ABC123"
                className="text-center text-3xl font-mono tracking-[0.4em] h-16"
              />
              <Button type="submit" className="w-full h-12" disabled={codeLoading || code.length !== 6}>
                {codeLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Continue →"}
              </Button>
            </form>
            <p className="text-xs text-center text-muted-foreground">
              Your code was generated by your tournament organizer in Team Members.
            </p>
          </div>

          {/* Email + password */}
          <div className="rounded-md border p-4 space-y-3">
            <p className="text-sm font-semibold flex items-center gap-2">
              <Mail className="h-4 w-4" /> Email &amp; Password
            </p>
            <form onSubmit={submitEmail} className="space-y-3">
              <div className="space-y-1.5">
                <Label htmlFor="tm-email">Email</Label>
                <Input
                  id="tm-email"
                  type="email"
                  autoComplete="email"
                  placeholder="you@example.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="tm-password">Password</Label>
                <Input
                  id="tm-password"
                  type="password"
                  autoComplete="current-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
              <Button type="submit" className="w-full" disabled={emailLoading}>
                {emailLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Sign In"}
              </Button>
            </form>
            <p className="text-xs text-muted-foreground">
              Forgot your password? <Link className="underline" to="/reset-password">Reset it here</Link>.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
