/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CollegeIndexRouteImport } from './routes/college/index'
import { Route as CollegeSlugRouteImport } from './routes/college/$slug'
import { Route as LeagueSlugRouteImport } from './routes/league/$slug'
import { Route as PairingsSlugRouteImport } from './routes/pairings/$slug'
import { Route as SSlugRouteImport } from './routes/s/$slug'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as TeamSlugRouteImport } from './routes/team/$slug'
import { Route as TournamentSlugRouteImport } from './routes/tournament/$slug'
import { Route as ApiPublicLeadMagnetDownloadRouteImport } from './routes/api/public/lead-magnet-download'
import { Route as ApiPublicLeagueEventConfirmationRouteImport } from './routes/api/public/league-event-confirmation'
import { Route as ApiPublicLeagueEventRegistrationLinkRouteImport } from './routes/api/public/league-event-registration-link'
import { Route as ApiPublicLeagueLoginInstructionsRouteImport } from './routes/api/public/league-login-instructions'
import { Route as ApiPublicLeaguePaymentConfirmRouteImport } from './routes/api/public/league-payment-confirm'
import { Route as ApiPublicNewsletterSendRouteImport } from './routes/api/public/newsletter-send'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter-unsubscribe'
import { Route as ApiPublicPostEventOrganizerEmailRouteImport } from './routes/api/public/post-event-organizer-email'
import { Route as ApiPublicSampleRequestRouteImport } from './routes/api/public/sample-request'
import { Route as SSassurveyShareRouteImport } from './routes/s/sassurvey/share'
import { Route as TeamSlugStarterRouteImport } from './routes/team/$slug.starter'
import { Route as ApiPublicHooksCheckTournamentLinksRouteImport } from './routes/api/public/hooks/check-tournament-links'
import { Route as ApiPublicHooksLeadMagnetFollowupsRouteImport } from './routes/api/public/hooks/lead-magnet-followups'
import { Route as ApiPublicHooksProcessScheduledEmailsRouteImport } from './routes/api/public/hooks/process-scheduled-emails'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/college/',
  path: '/college/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeSlugRoute = CollegeSlugRouteImport.update({
  id: '/college/$slug',
  path: '/college/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueSlugRoute = LeagueSlugRouteImport.update({
  id: '/league/$slug',
  path: '/league/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingsSlugRoute = PairingsSlugRouteImport.update({
  id: '/pairings/$slug',
  path: '/pairings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentSlugRoute = TournamentSlugRouteImport.update({
  id: '/tournament/$slug',
  path: '/tournament/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadMagnetDownloadRoute =
  ApiPublicLeadMagnetDownloadRouteImport.update({
    id: '/api/public/lead-magnet-download',
    path: '/api/public/lead-magnet-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeagueEventConfirmationRoute =
  ApiPublicLeagueEventConfirmationRouteImport.update({
    id: '/api/public/league-event-confirmation',
    path: '/api/public/league-event-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeagueEventRegistrationLinkRoute =
  ApiPublicLeagueEventRegistrationLinkRouteImport.update({
    id: '/api/public/league-event-registration-link',
    path: '/api/public/league-event-registration-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeagueLoginInstructionsRoute =
  ApiPublicLeagueLoginInstructionsRouteImport.update({
    id: '/api/public/league-login-instructions',
    path: '/api/public/league-login-instructions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeaguePaymentConfirmRoute =
  ApiPublicLeaguePaymentConfirmRouteImport.update({
    id: '/api/public/league-payment-confirm',
    path: '/api/public/league-payment-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterSendRoute = ApiPublicNewsletterSendRouteImport.update({
  id: '/api/public/newsletter-send',
  path: '/api/public/newsletter-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter-unsubscribe',
    path: '/api/public/newsletter-unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostEventOrganizerEmailRoute =
  ApiPublicPostEventOrganizerEmailRouteImport.update({
    id: '/api/public/post-event-organizer-email',
    path: '/api/public/post-event-organizer-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSampleRequestRoute = ApiPublicSampleRequestRouteImport.update({
  id: '/api/public/sample-request',
  path: '/api/public/sample-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SSassurveyShareRoute = SSassurveyShareRouteImport.update({
  id: '/s/sassurvey/share',
  path: '/s/sassurvey/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugStarterRoute = TeamSlugStarterRouteImport.update({
  id: '/starter',
  path: '/starter',
  getParentRoute: () => TeamSlugRoute,
} as any)
const ApiPublicHooksCheckTournamentLinksRoute =
  ApiPublicHooksCheckTournamentLinksRouteImport.update({
    id: '/api/public/hooks/check-tournament-links',
    path: '/api/public/hooks/check-tournament-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadMagnetFollowupsRoute =
  ApiPublicHooksLeadMagnetFollowupsRouteImport.update({
    id: '/api/public/hooks/lead-magnet-followups',
    path: '/api/public/hooks/lead-magnet-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessScheduledEmailsRoute =
  ApiPublicHooksProcessScheduledEmailsRouteImport.update({
    id: '/api/public/hooks/process-scheduled-emails',
    path: '/api/public/hooks/process-scheduled-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/pairings/$slug': typeof PairingsSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college/': typeof CollegeIndexRoute
  '/api/public/lead-magnet-download': typeof ApiPublicLeadMagnetDownloadRoute
  '/api/public/league-event-confirmation': typeof ApiPublicLeagueEventConfirmationRoute
  '/api/public/league-event-registration-link': typeof ApiPublicLeagueEventRegistrationLinkRoute
  '/api/public/league-login-instructions': typeof ApiPublicLeagueLoginInstructionsRoute
  '/api/public/league-payment-confirm': typeof ApiPublicLeaguePaymentConfirmRoute
  '/api/public/newsletter-send': typeof ApiPublicNewsletterSendRoute
  '/api/public/newsletter-unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/api/public/post-event-organizer-email': typeof ApiPublicPostEventOrganizerEmailRoute
  '/api/public/sample-request': typeof ApiPublicSampleRequestRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
  '/team/$slug/starter': typeof TeamSlugStarterRoute
  '/api/public/hooks/check-tournament-links': typeof ApiPublicHooksCheckTournamentLinksRoute
  '/api/public/hooks/lead-magnet-followups': typeof ApiPublicHooksLeadMagnetFollowupsRoute
  '/api/public/hooks/process-scheduled-emails': typeof ApiPublicHooksProcessScheduledEmailsRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/pairings/$slug': typeof PairingsSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college': typeof CollegeIndexRoute
  '/api/public/lead-magnet-download': typeof ApiPublicLeadMagnetDownloadRoute
  '/api/public/league-event-confirmation': typeof ApiPublicLeagueEventConfirmationRoute
  '/api/public/league-event-registration-link': typeof ApiPublicLeagueEventRegistrationLinkRoute
  '/api/public/league-login-instructions': typeof ApiPublicLeagueLoginInstructionsRoute
  '/api/public/league-payment-confirm': typeof ApiPublicLeaguePaymentConfirmRoute
  '/api/public/newsletter-send': typeof ApiPublicNewsletterSendRoute
  '/api/public/newsletter-unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/api/public/post-event-organizer-email': typeof ApiPublicPostEventOrganizerEmailRoute
  '/api/public/sample-request': typeof ApiPublicSampleRequestRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
  '/team/$slug/starter': typeof TeamSlugStarterRoute
  '/api/public/hooks/check-tournament-links': typeof ApiPublicHooksCheckTournamentLinksRoute
  '/api/public/hooks/lead-magnet-followups': typeof ApiPublicHooksLeadMagnetFollowupsRoute
  '/api/public/hooks/process-scheduled-emails': typeof ApiPublicHooksProcessScheduledEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/pairings/$slug': typeof PairingsSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/team/$slug': typeof TeamSlugRouteWithChildren
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college/': typeof CollegeIndexRoute
  '/api/public/lead-magnet-download': typeof ApiPublicLeadMagnetDownloadRoute
  '/api/public/league-event-confirmation': typeof ApiPublicLeagueEventConfirmationRoute
  '/api/public/league-event-registration-link': typeof ApiPublicLeagueEventRegistrationLinkRoute
  '/api/public/league-login-instructions': typeof ApiPublicLeagueLoginInstructionsRoute
  '/api/public/league-payment-confirm': typeof ApiPublicLeaguePaymentConfirmRoute
  '/api/public/newsletter-send': typeof ApiPublicNewsletterSendRoute
  '/api/public/newsletter-unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/api/public/post-event-organizer-email': typeof ApiPublicPostEventOrganizerEmailRoute
  '/api/public/sample-request': typeof ApiPublicSampleRequestRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
  '/team/$slug/starter': typeof TeamSlugStarterRoute
  '/api/public/hooks/check-tournament-links': typeof ApiPublicHooksCheckTournamentLinksRoute
  '/api/public/hooks/lead-magnet-followups': typeof ApiPublicHooksLeadMagnetFollowupsRoute
  '/api/public/hooks/process-scheduled-emails': typeof ApiPublicHooksProcessScheduledEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/sitemap.xml'
    | '/college/$slug'
    | '/league/$slug'
    | '/pairings/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/team/$slug'
    | '/tournament/$slug'
    | '/college/'
    | '/api/public/lead-magnet-download'
    | '/api/public/league-event-confirmation'
    | '/api/public/league-event-registration-link'
    | '/api/public/league-login-instructions'
    | '/api/public/league-payment-confirm'
    | '/api/public/newsletter-send'
    | '/api/public/newsletter-unsubscribe'
    | '/api/public/post-event-organizer-email'
    | '/api/public/sample-request'
    | '/s/sassurvey/share'
    | '/team/$slug/starter'
    | '/api/public/hooks/check-tournament-links'
    | '/api/public/hooks/lead-magnet-followups'
    | '/api/public/hooks/process-scheduled-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/sitemap.xml'
    | '/college/$slug'
    | '/league/$slug'
    | '/pairings/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/team/$slug'
    | '/tournament/$slug'
    | '/college'
    | '/api/public/lead-magnet-download'
    | '/api/public/league-event-confirmation'
    | '/api/public/league-event-registration-link'
    | '/api/public/league-login-instructions'
    | '/api/public/league-payment-confirm'
    | '/api/public/newsletter-send'
    | '/api/public/newsletter-unsubscribe'
    | '/api/public/post-event-organizer-email'
    | '/api/public/sample-request'
    | '/s/sassurvey/share'
    | '/team/$slug/starter'
    | '/api/public/hooks/check-tournament-links'
    | '/api/public/hooks/lead-magnet-followups'
    | '/api/public/hooks/process-scheduled-emails'
  id:
    | '__root__'
    | '/$'
    | '/sitemap.xml'
    | '/college/$slug'
    | '/league/$slug'
    | '/pairings/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/team/$slug'
    | '/tournament/$slug'
    | '/college/'
    | '/api/public/lead-magnet-download'
    | '/api/public/league-event-confirmation'
    | '/api/public/league-event-registration-link'
    | '/api/public/league-login-instructions'
    | '/api/public/league-payment-confirm'
    | '/api/public/newsletter-send'
    | '/api/public/newsletter-unsubscribe'
    | '/api/public/post-event-organizer-email'
    | '/api/public/sample-request'
    | '/s/sassurvey/share'
    | '/team/$slug/starter'
    | '/api/public/hooks/check-tournament-links'
    | '/api/public/hooks/lead-magnet-followups'
    | '/api/public/hooks/process-scheduled-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CollegeSlugRoute: typeof CollegeSlugRoute
  LeagueSlugRoute: typeof LeagueSlugRoute
  PairingsSlugRoute: typeof PairingsSlugRoute
  SSlugRoute: typeof SSlugRoute
  TSlugRoute: typeof TSlugRoute
  TeamSlugRoute: typeof TeamSlugRouteWithChildren
  TournamentSlugRoute: typeof TournamentSlugRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
  ApiPublicLeadMagnetDownloadRoute: typeof ApiPublicLeadMagnetDownloadRoute
  ApiPublicLeagueEventConfirmationRoute: typeof ApiPublicLeagueEventConfirmationRoute
  ApiPublicLeagueEventRegistrationLinkRoute: typeof ApiPublicLeagueEventRegistrationLinkRoute
  ApiPublicLeagueLoginInstructionsRoute: typeof ApiPublicLeagueLoginInstructionsRoute
  ApiPublicLeaguePaymentConfirmRoute: typeof ApiPublicLeaguePaymentConfirmRoute
  ApiPublicNewsletterSendRoute: typeof ApiPublicNewsletterSendRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
  ApiPublicPostEventOrganizerEmailRoute: typeof ApiPublicPostEventOrganizerEmailRoute
  ApiPublicSampleRequestRoute: typeof ApiPublicSampleRequestRoute
  SSassurveyShareRoute: typeof SSassurveyShareRoute
  ApiPublicHooksCheckTournamentLinksRoute: typeof ApiPublicHooksCheckTournamentLinksRoute
  ApiPublicHooksLeadMagnetFollowupsRoute: typeof ApiPublicHooksLeadMagnetFollowupsRoute
  ApiPublicHooksProcessScheduledEmailsRoute: typeof ApiPublicHooksProcessScheduledEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/': {
      id: '/college/'
      path: '/college'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/$slug': {
      id: '/college/$slug'
      path: '/college/$slug'
      fullPath: '/college/$slug'
      preLoaderRoute: typeof CollegeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$slug': {
      id: '/league/$slug'
      path: '/league/$slug'
      fullPath: '/league/$slug'
      preLoaderRoute: typeof LeagueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairings/$slug': {
      id: '/pairings/$slug'
      path: '/pairings/$slug'
      fullPath: '/pairings/$slug'
      preLoaderRoute: typeof PairingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$slug': {
      id: '/tournament/$slug'
      path: '/tournament/$slug'
      fullPath: '/tournament/$slug'
      preLoaderRoute: typeof TournamentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-magnet-download': {
      id: '/api/public/lead-magnet-download'
      path: '/api/public/lead-magnet-download'
      fullPath: '/api/public/lead-magnet-download'
      preLoaderRoute: typeof ApiPublicLeadMagnetDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/league-event-confirmation': {
      id: '/api/public/league-event-confirmation'
      path: '/api/public/league-event-confirmation'
      fullPath: '/api/public/league-event-confirmation'
      preLoaderRoute: typeof ApiPublicLeagueEventConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/league-event-registration-link': {
      id: '/api/public/league-event-registration-link'
      path: '/api/public/league-event-registration-link'
      fullPath: '/api/public/league-event-registration-link'
      preLoaderRoute: typeof ApiPublicLeagueEventRegistrationLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/league-login-instructions': {
      id: '/api/public/league-login-instructions'
      path: '/api/public/league-login-instructions'
      fullPath: '/api/public/league-login-instructions'
      preLoaderRoute: typeof ApiPublicLeagueLoginInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/league-payment-confirm': {
      id: '/api/public/league-payment-confirm'
      path: '/api/public/league-payment-confirm'
      fullPath: '/api/public/league-payment-confirm'
      preLoaderRoute: typeof ApiPublicLeaguePaymentConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-send': {
      id: '/api/public/newsletter-send'
      path: '/api/public/newsletter-send'
      fullPath: '/api/public/newsletter-send'
      preLoaderRoute: typeof ApiPublicNewsletterSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-unsubscribe': {
      id: '/api/public/newsletter-unsubscribe'
      path: '/api/public/newsletter-unsubscribe'
      fullPath: '/api/public/newsletter-unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-event-organizer-email': {
      id: '/api/public/post-event-organizer-email'
      path: '/api/public/post-event-organizer-email'
      fullPath: '/api/public/post-event-organizer-email'
      preLoaderRoute: typeof ApiPublicPostEventOrganizerEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sample-request': {
      id: '/api/public/sample-request'
      path: '/api/public/sample-request'
      fullPath: '/api/public/sample-request'
      preLoaderRoute: typeof ApiPublicSampleRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/sassurvey/share': {
      id: '/s/sassurvey/share'
      path: '/s/sassurvey/share'
      fullPath: '/s/sassurvey/share'
      preLoaderRoute: typeof SSassurveyShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug/starter': {
      id: '/team/$slug/starter'
      path: '/starter'
      fullPath: '/team/$slug/starter'
      preLoaderRoute: typeof TeamSlugStarterRouteImport
      parentRoute: typeof TeamSlugRoute
    }
    '/api/public/hooks/check-tournament-links': {
      id: '/api/public/hooks/check-tournament-links'
      path: '/api/public/hooks/check-tournament-links'
      fullPath: '/api/public/hooks/check-tournament-links'
      preLoaderRoute: typeof ApiPublicHooksCheckTournamentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-magnet-followups': {
      id: '/api/public/hooks/lead-magnet-followups'
      path: '/api/public/hooks/lead-magnet-followups'
      fullPath: '/api/public/hooks/lead-magnet-followups'
      preLoaderRoute: typeof ApiPublicHooksLeadMagnetFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scheduled-emails': {
      id: '/api/public/hooks/process-scheduled-emails'
      path: '/api/public/hooks/process-scheduled-emails'
      fullPath: '/api/public/hooks/process-scheduled-emails'
      preLoaderRoute: typeof ApiPublicHooksProcessScheduledEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamSlugRouteChildren {
  TeamSlugStarterRoute: typeof TeamSlugStarterRoute
}

const TeamSlugRouteChildren: TeamSlugRouteChildren = {
  TeamSlugStarterRoute: TeamSlugStarterRoute,
}

const TeamSlugRouteWithChildren = TeamSlugRoute._addFileChildren(
  TeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CollegeSlugRoute: CollegeSlugRoute,
  LeagueSlugRoute: LeagueSlugRoute,
  PairingsSlugRoute: PairingsSlugRoute,
  SSlugRoute: SSlugRoute,
  TSlugRoute: TSlugRoute,
  TeamSlugRoute: TeamSlugRouteWithChildren,
  TournamentSlugRoute: TournamentSlugRoute,
  CollegeIndexRoute: CollegeIndexRoute,
  ApiPublicLeadMagnetDownloadRoute: ApiPublicLeadMagnetDownloadRoute,
  ApiPublicLeagueEventConfirmationRoute: ApiPublicLeagueEventConfirmationRoute,
  ApiPublicLeagueEventRegistrationLinkRoute:
    ApiPublicLeagueEventRegistrationLinkRoute,
  ApiPublicLeagueLoginInstructionsRoute: ApiPublicLeagueLoginInstructionsRoute,
  ApiPublicLeaguePaymentConfirmRoute: ApiPublicLeaguePaymentConfirmRoute,
  ApiPublicNewsletterSendRoute: ApiPublicNewsletterSendRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
  ApiPublicPostEventOrganizerEmailRoute: ApiPublicPostEventOrganizerEmailRoute,
  ApiPublicSampleRequestRoute: ApiPublicSampleRequestRoute,
  SSassurveyShareRoute: SSassurveyShareRoute,
  ApiPublicHooksCheckTournamentLinksRoute:
    ApiPublicHooksCheckTournamentLinksRoute,
  ApiPublicHooksLeadMagnetFollowupsRoute:
    ApiPublicHooksLeadMagnetFollowupsRoute,
  ApiPublicHooksProcessScheduledEmailsRoute:
    ApiPublicHooksProcessScheduledEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
