/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CollegeIndexRouteImport } from './routes/college/index'
import { Route as CollegeSlugRouteImport } from './routes/college/$slug'
import { Route as SSlugRouteImport } from './routes/s/$slug'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as TournamentSlugRouteImport } from './routes/tournament/$slug'
import { Route as SSassurveyShareRouteImport } from './routes/s/sassurvey/share'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/college/',
  path: '/college/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeSlugRoute = CollegeSlugRouteImport.update({
  id: '/college/$slug',
  path: '/college/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentSlugRoute = TournamentSlugRouteImport.update({
  id: '/tournament/$slug',
  path: '/tournament/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSassurveyShareRoute = SSassurveyShareRouteImport.update({
  id: '/s/sassurvey/share',
  path: '/s/sassurvey/share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college/': typeof CollegeIndexRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college': typeof CollegeIndexRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
  '/college/': typeof CollegeIndexRoute
  '/s/sassurvey/share': typeof SSassurveyShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/college/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/tournament/$slug'
    | '/college/'
    | '/s/sassurvey/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/college/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/tournament/$slug'
    | '/college'
    | '/s/sassurvey/share'
  id:
    | '__root__'
    | '/$'
    | '/college/$slug'
    | '/s/$slug'
    | '/t/$slug'
    | '/tournament/$slug'
    | '/college/'
    | '/s/sassurvey/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CollegeSlugRoute: typeof CollegeSlugRoute
  SSlugRoute: typeof SSlugRoute
  TSlugRoute: typeof TSlugRoute
  TournamentSlugRoute: typeof TournamentSlugRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
  SSassurveyShareRoute: typeof SSassurveyShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/': {
      id: '/college/'
      path: '/college'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/$slug': {
      id: '/college/$slug'
      path: '/college/$slug'
      fullPath: '/college/$slug'
      preLoaderRoute: typeof CollegeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$slug': {
      id: '/tournament/$slug'
      path: '/tournament/$slug'
      fullPath: '/tournament/$slug'
      preLoaderRoute: typeof TournamentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/sassurvey/share': {
      id: '/s/sassurvey/share'
      path: '/s/sassurvey/share'
      fullPath: '/s/sassurvey/share'
      preLoaderRoute: typeof SSassurveyShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CollegeSlugRoute: CollegeSlugRoute,
  SSlugRoute: SSlugRoute,
  TSlugRoute: TSlugRoute,
  TournamentSlugRoute: TournamentSlugRoute,
  CollegeIndexRoute: CollegeIndexRoute,
  SSassurveyShareRoute: SSassurveyShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
