/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CollegeSlugRouteImport } from './routes/college/$slug'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as TournamentSlugRouteImport } from './routes/tournament/$slug'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeSlugRoute = CollegeSlugRouteImport.update({
  id: '/college/$slug',
  path: '/college/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentSlugRoute = TournamentSlugRouteImport.update({
  id: '/tournament/$slug',
  path: '/tournament/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/college/$slug': typeof CollegeSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/college/$slug' | '/t/$slug' | '/tournament/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/college/$slug' | '/t/$slug' | '/tournament/$slug'
  id: '__root__' | '/$' | '/college/$slug' | '/t/$slug' | '/tournament/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CollegeSlugRoute: typeof CollegeSlugRoute
  TSlugRoute: typeof TSlugRoute
  TournamentSlugRoute: typeof TournamentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/$slug': {
      id: '/college/$slug'
      path: '/college/$slug'
      fullPath: '/college/$slug'
      preLoaderRoute: typeof CollegeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$slug': {
      id: '/tournament/$slug'
      path: '/tournament/$slug'
      fullPath: '/tournament/$slug'
      preLoaderRoute: typeof TournamentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CollegeSlugRoute: CollegeSlugRoute,
  TSlugRoute: TSlugRoute,
  TournamentSlugRoute: TournamentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
