// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-tournaments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_tournaments_default = defineTool({
  name: "list_my_tournaments",
  title: "List my tournaments",
  description: "List tournaments the signed-in organizer has access to. Returns id, title, date, course, status, and public URL slug.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient(ctx).from("tournaments").select("id, title, date, course_name, site_published, custom_slug, registration_open, registration_fee_cents").order("date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tournaments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tournament-registrations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_tournament_registrations_default = defineTool2({
  name: "get_tournament_registrations",
  title: "Get tournament registrations",
  description: "List registrations for a tournament the signed-in organizer owns. Returns player names, email, group, and payment status.",
  inputSchema: {
    tournament_id: z2.string().uuid().describe("The tournament UUID."),
    limit: z2.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tournament_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient2(ctx).from("tournament_registrations").select("id, first_name, last_name, email, phone, group_number, payment_status, created_at").eq("tournament_id", tournament_id).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { registrations: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/search-public-tournaments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_public_tournaments_default = defineTool3({
  name: "search_public_tournaments",
  title: "Search public tournaments",
  description: "Search TeeVents tournaments that have opted into public discovery. Returns id, title, date, course, and public slug.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search text matched against tournament title or course."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const like = `%${query}%`;
    const { data, error } = await anonClient().from("tournaments").select("id, title, date, course_name, custom_slug").eq("show_in_public_search", true).eq("site_published", true).or(`title.ilike.${like},course_name.ilike.${like}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wmoivwwerxqscqznivnn";
var mcp_default = defineMcp({
  name: "teevents-mcp",
  title: "TeeVents",
  version: "0.1.0",
  instructions: "Tools for TeeVents, a golf tournament management platform. Use `list_my_tournaments` to see the signed-in organizer's tournaments, `get_tournament_registrations` to inspect registrations for a specific tournament, and `search_public_tournaments` to find publicly listed tournaments (no auth required).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_tournaments_default, get_tournament_registrations_default, search_public_tournaments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
