
ALTER TABLE public.budget_income
  ADD COLUMN IF NOT EXISTS quantity_estimated INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quantity_actual INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12,2) NOT NULL DEFAULT 0;
