INSERT INTO public.lead_magnets (title, slug, description, article_type, is_published, content) VALUES
('Golf Tournament Planning Checklist', 'golf-tournament-planning-checklist',
 'A step-by-step checklist to help you plan and execute a successful golf tournament. Includes timelines, sponsor tips, and a day-of checklist.',
 'checklist', true,
 '<h2>12 Months Out</h2><ul><li>Select your course and lock the date</li><li>Set a budget with revenue and expense targets</li><li>Build your sponsor prospect list</li><li>Choose your tournament format</li></ul><h2>6 Months Out</h2><ul><li>Open online registration with clear pricing</li><li>Publish your tournament page and share the link</li><li>Send the first sponsor outreach round</li><li>Order signage, prizes, and player gifts</li></ul><h2>3 Months Out</h2><ul><li>Draft pairings and team groupings</li><li>Set shotgun start or tee time intervals</li><li>Recruit volunteers and assign roles</li><li>Confirm auction, raffle, and contest holes</li></ul><h2>1 Month Out</h2><ul><li>Finalize the roster and collect outstanding payments</li><li>Confirm the course headcount and food order</li><li>Print scorecards, cart signs, and name badges</li><li>Send player reminder emails with tee times</li></ul><h2>Event Day</h2><ul><li>Set up check-in and hand out scoring codes</li><li>Run live scoring and the leaderboard</li><li>Rotate sponsor recognition throughout the day</li><li>Award ceremony and prize distribution</li></ul><h2>Post-Event</h2><ul><li>Send thank-you notes to sponsors and players</li><li>Send a post-event survey</li><li>Reconcile finances and report funds raised</li><li>Set next year''s date while momentum is high</li></ul>'),
('Golf Tournament Sponsor Package Template', 'golf-tournament-sponsor-package-template',
 'A customizable template for building sponsor packages, including levels, benefits, pricing guidance, and an agreement form.',
 'html', true,
 '<h2>Sponsorship Levels</h2><h3>Title Sponsor — $10,000</h3><ul><li>Event naming rights and top logo placement</li><li>Two foursomes with premium tee times</li><li>Logo on the live leaderboard and all emails</li><li>Speaking moment at the awards ceremony</li></ul><h3>Gold — $5,000</h3><ul><li>Logo on the tournament page and banner</li><li>One foursome</li><li>Two hole signs</li></ul><h3>Silver — $2,500</h3><ul><li>Logo on the tournament page</li><li>Two players</li><li>One hole sign</li></ul><h3>Bronze — $1,000</h3><ul><li>Hole sign and program listing</li></ul><h2>Pricing Recommendations</h2><p>Price your title sponsorship at roughly 10-15% of your fundraising goal, and keep at least three lower tiers so small local businesses can participate. Cart signs and contest holes ($250-$500) convert fastest.</p><h2>Logo Placement Options</h2><ul><li>Public tournament page and registration checkout</li><li>Rotating banner and scrolling ticker on the live leaderboard</li><li>Cart signs, scorecards, and hole signage</li><li>Confirmation and reminder emails</li></ul><h2>Sponsor Agreement Form</h2><p>Company, contact name, email, phone, sponsorship level, payment method, logo file, and signature with date. Include your tax ID and 501(c)(3) status if applicable.</p>'),
('Tournament Pairings & Tee Times Guide', 'tournament-pairings-tee-times-guide',
 'How to create fair, efficient pairings and tee times — including shotgun versus tee time starts and handling player requests.',
 'html', true,
 '<h2>Grouping Players by Handicap</h2><p>Balanced groups keep scoring competitive. For team formats, blend one low, two mid, and one higher handicap per group. For individual stroke play, group similar handicaps so pace of play stays even.</p><h2>Tee Time Scheduling</h2><ul><li>Use 8-10 minute intervals for foursomes</li><li>Start from Hole 1 and Hole 10 together to cut your window in half</li><li>Leave a gap for late arrivals and walk-up registrations</li></ul><h2>Shotgun Start vs. Tee Time Start</h2><p>A shotgun start puts every group on a different hole at the same time — best for large fields, sponsor visibility, and a single awards ceremony. Tee time starts suit smaller fields, multi-day events, and courses with public play.</p><h2>Managing Player Requests</h2><ul><li>Collect requests at registration, not by email</li><li>Honor sponsor foursomes first, then captain requests</li><li>Publish pairings only after you lock them to avoid rework</li></ul>'),
('Golf Tournament Scoring Formats Explained', 'golf-tournament-scoring-formats-explained',
 'Plain-English explanations of the most common tournament scoring formats, with examples of when to use each.',
 'html', true,
 '<h2>Scramble</h2><p>Every player hits, the team picks the best shot, and everyone plays from there. Fast, forgiving, and the best choice for charity events with mixed skill levels.</p><h2>Best Ball</h2><p>Each player plays their own ball; the team score is the lowest score on each hole. Rewards strong individual play while keeping everyone involved.</p><h2>Stroke Play</h2><p>Total strokes over the round. The purest test and the standard for competitive fields.</p><h2>Match Play</h2><p>Hole-by-hole competition between two players or teams. Scored as holes up, not total strokes.</p><h2>Stableford</h2><p>Points awarded relative to par (eagle 4, birdie 3, par 2, bogey 1). Keeps slower players engaged because one bad hole does not ruin a round.</p><h2>Skins</h2><p>A side game where the low score on each hole wins the skin. Ties carry over. Easy to add as a paid upgrade at registration.</p>'),
('Charity Golf Tournament Fundraising Guide', 'charity-golf-tournament-fundraising-guide',
 'How to maximize the money your charity tournament raises — sponsor recruitment, auctions and raffles, donation strategies, and follow-up.',
 'html', true,
 '<h2>Sponsor Recruitment</h2><p>Start with board members, past donors, and local businesses that serve your community. Lead with impact, not logo size — show exactly what their dollars fund.</p><h2>Auctions and Raffles</h2><ul><li>Run a silent auction online so bidding starts before event day</li><li>Use a 50/50 raffle for easy cash-flow wins</li><li>Keep 15-25 auction items — quality beats quantity</li></ul><h2>Donation Strategies</h2><ul><li>Add a donation option at registration checkout</li><li>Offer sponsor-a-player and sponsor-a-veteran options</li><li>Promote mulligans, contest entries, and skins as add-ons</li><li>Issue tax receipts automatically for 501(c)(3) events</li></ul><h2>Post-Event Follow-Up</h2><p>Report the total raised within one week, thank every sponsor by name, and share photos. That report is your best sponsor renewal tool for next year.</p>'),
('Live Scoring & Leaderboard Guide', 'live-scoring-leaderboard-guide',
 'How live scoring works, how players enter scores, and how to put sponsors in front of every player all day.',
 'html', true,
 '<h2>QR Code Scoring</h2><p>Each group gets a printed scoring code on the cart sign or scorecard. Players scan the QR code, enter the code once, and score from their phone all day — no app install and no passwords.</p><h2>How Players Enter Scores</h2><ul><li>One score per group for team formats like scramble</li><li>Confirm the hole and advance automatically to the next one</li><li>Scores queue offline and sync when signal returns</li></ul><h2>Leaderboard Display Options</h2><ul><li>Big-screen view for the clubhouse or pavilion</li><li>Mobile view players refresh from the course</li><li>Flight and division filters for multi-tier fields</li></ul><h2>Sponsor Logos on the Leaderboard</h2><p>Rotate sponsor banners at the top of the leaderboard and run a scrolling ticker of every sponsor. It is the highest-visibility placement you can sell, because players check the leaderboard dozens of times per round.</p>');

INSERT INTO public.lead_magnet_article_categories (article_id, category_id)
SELECT m.id, c.id FROM public.lead_magnets m, public.lead_magnet_categories c
WHERE (m.slug IN ('golf-tournament-planning-checklist') AND c.slug = 'planning')
   OR (m.slug IN ('golf-tournament-sponsor-package-template','charity-golf-tournament-fundraising-guide') AND c.slug = 'sponsors-fundraising')
   OR (m.slug IN ('tournament-pairings-tee-times-guide','golf-tournament-scoring-formats-explained','live-scoring-leaderboard-guide') AND c.slug = 'scoring-day-of')
ON CONFLICT DO NOTHING;