
ALTER TABLE public.golf_leagues
  ADD COLUMN IF NOT EXISTS tagline TEXT,
  ADD COLUMN IF NOT EXISTS welcome_message TEXT,
  ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#1a5c38',
  ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#F5A623',
  ADD COLUMN IF NOT EXISTS font_color TEXT DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS show_schedule BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_standings BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_results BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_register BOOLEAN NOT NULL DEFAULT TRUE;
